# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kristof/Documents/codes/sdl/phystest

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kristof/Documents/codes/sdl/phystest

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kristof/Documents/codes/sdl/phystest/CMakeFiles /home/kristof/Documents/codes/sdl/phystest/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kristof/Documents/codes/sdl/phystest/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named phystest

# Build rule for target.
phystest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 phystest
.PHONY : phystest

# fast build rule for target.
phystest/fast:
	$(MAKE) -f CMakeFiles/phystest.dir/build.make CMakeFiles/phystest.dir/build
.PHONY : phystest/fast

AABB.o: AABB.cpp.o

.PHONY : AABB.o

# target to build an object file
AABB.cpp.o:
	$(MAKE) -f CMakeFiles/phystest.dir/build.make CMakeFiles/phystest.dir/AABB.cpp.o
.PHONY : AABB.cpp.o

AABB.i: AABB.cpp.i

.PHONY : AABB.i

# target to preprocess a source file
AABB.cpp.i:
	$(MAKE) -f CMakeFiles/phystest.dir/build.make CMakeFiles/phystest.dir/AABB.cpp.i
.PHONY : AABB.cpp.i

AABB.s: AABB.cpp.s

.PHONY : AABB.s

# target to generate assembly for a file
AABB.cpp.s:
	$(MAKE) -f CMakeFiles/phystest.dir/build.make CMakeFiles/phystest.dir/AABB.cpp.s
.PHONY : AABB.cpp.s

SDLWrapper.o: SDLWrapper.cpp.o

.PHONY : SDLWrapper.o

# target to build an object file
SDLWrapper.cpp.o:
	$(MAKE) -f CMakeFiles/phystest.dir/build.make CMakeFiles/phystest.dir/SDLWrapper.cpp.o
.PHONY : SDLWrapper.cpp.o

SDLWrapper.i: SDLWrapper.cpp.i

.PHONY : SDLWrapper.i

# target to preprocess a source file
SDLWrapper.cpp.i:
	$(MAKE) -f CMakeFiles/phystest.dir/build.make CMakeFiles/phystest.dir/SDLWrapper.cpp.i
.PHONY : SDLWrapper.cpp.i

SDLWrapper.s: SDLWrapper.cpp.s

.PHONY : SDLWrapper.s

# target to generate assembly for a file
SDLWrapper.cpp.s:
	$(MAKE) -f CMakeFiles/phystest.dir/build.make CMakeFiles/phystest.dir/SDLWrapper.cpp.s
.PHONY : SDLWrapper.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/phystest.dir/build.make CMakeFiles/phystest.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/phystest.dir/build.make CMakeFiles/phystest.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/phystest.dir/build.make CMakeFiles/phystest.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... phystest"
	@echo "... AABB.o"
	@echo "... AABB.i"
	@echo "... AABB.s"
	@echo "... SDLWrapper.o"
	@echo "... SDLWrapper.i"
	@echo "... SDLWrapper.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

